# Generated by Django 3.1.3 on 2021-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
