# Generated by Django 3.1.3 on 2021-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20210114_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='is_completed',
            new_name='is_ended',
        ),
    ]
