# Generated by Django 3.1.3 on 2021-01-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20210114_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
