# Generated by Django 3.1.3 on 2021-01-15 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0004_auto_20210114_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Charity', 'Charity'), ('Clothing', 'Clothing'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Groceries', 'Groceries'), ('Hobbies', 'Hobbies'), ('Incidentials', 'Incidentials'), ('Medical', 'Medical'), ('Rent', 'Rent'), ('Personal Care', 'Personal Care'), ('Pets', 'Pets'), ('School', 'School'), ('Utilities', 'Utilities'), ('Vacation', 'Vacation'), ('Work', 'Work')], default='Car', max_length=200, null=True)),
                ('currency', models.CharField(choices=[('SGD', 'SGD'), ('MYR', 'MYR')], default='SGD', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
