# Generated by Django 3.1.3 on 2021-01-15 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_dailyexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexpense',
            old_name='title',
            new_name='expense_title',
        ),
    ]
