# Generated by Django 3.1.3 on 2021-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20210115_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='currency',
            field=models.CharField(default='SGD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='type',
            field=models.CharField(default='Groceries', max_length=200, null=True),
        ),
    ]
