# Generated by Django 3.1.3 on 2021-01-15 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20210116_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 0, 44, 29, 168165)),
        ),
    ]
