# Generated by Django 3.1.3 on 2021-01-18 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20210116_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 14, 54, 53, 572873)),
        ),
    ]
