# Generated by Django 3.1.3 on 2021-01-18 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20210118_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 15, 6, 27, 439407)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
