# Generated by Django 3.1.3 on 2021-01-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20210118_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 18, 16, 39, 967373)),
        ),
    ]
